version: '3.8'

services:
  # Data Collector Service
  data-collector:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.collector
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - ODDS_API_KEY=${ODDS_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - BALLDONTLIE_API_KEY=${BALLDONTLIE_API_KEY}
    volumes:
      - collector-logs:/app/logs
    networks:
      - fantasy-network

  # ML Training Service  
  ml-trainer:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.ml
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ml-models:/app/models
      - ml-logs:/app/logs
    networks:
      - fantasy-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fantasy-network

volumes:
  collector-logs:
  ml-models:
  ml-logs:
  redis-data:

networks:
  fantasy-network:
    driver: bridge